/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author julian
 */
public class ConsultarAdicionales extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasAdicionales
     */
    public ConsultarAdicionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPlanEsRegisradoCurso = new javax.swing.JButton();
        btnCorrequisitoCurso = new javax.swing.JButton();
        btnRequisitoCurso = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Consultas adicionales");

        btnPlanEsRegisradoCurso.setText("Planes de Estudio registrados a Curso");
        btnPlanEsRegisradoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlanEsRegisradoCursoMouseClicked(evt);
            }
        });
        btnPlanEsRegisradoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanEsRegisradoCursoActionPerformed(evt);
            }
        });

        btnCorrequisitoCurso.setText("Correquisitos de Curso");
        btnCorrequisitoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCorrequisitoCursoMouseClicked(evt);
            }
        });

        btnRequisitoCurso.setText("Requisitos de Curso");
        btnRequisitoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRequisitoCursoMouseClicked(evt);
            }
        });
        btnRequisitoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequisitoCursoActionPerformed(evt);
            }
        });

        btnAtras.setText("atras");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRequisitoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCorrequisitoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlanEsRegisradoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnAtras)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(btnPlanEsRegisradoCurso)
                .addGap(44, 44, 44)
                .addComponent(btnRequisitoCurso)
                .addGap(43, 43, 43)
                .addComponent(btnCorrequisitoCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanEsRegisradoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanEsRegisradoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlanEsRegisradoCursoActionPerformed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
      MenuInicio menu = new MenuInicio();
      menu.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnPlanEsRegisradoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanEsRegisradoCursoMouseClicked
        // TODO add your handling code here:
      ConsultarPlanRegistradoCurso consultaPlanCurso = new ConsultarPlanRegistradoCurso();
      consultaPlanCurso.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnPlanEsRegisradoCursoMouseClicked

    private void btnRequisitoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequisitoCursoMouseClicked
        // TODO add your handling code here:
      ConsultarRequisitoCurso consultarRequisitoCurso = new ConsultarRequisitoCurso();
      consultarRequisitoCurso.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRequisitoCursoMouseClicked

    private void btnRequisitoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequisitoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequisitoCursoActionPerformed

    private void btnCorrequisitoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorrequisitoCursoMouseClicked
        // TODO add your handling code here:
      ConsultarCorrequisitoCurso consultarCorreCurso = new ConsultarCorrequisitoCurso(); 
      consultarCorreCurso.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnCorrequisitoCursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarAdicionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarAdicionales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCorrequisitoCurso;
    private javax.swing.JButton btnPlanEsRegisradoCurso;
    private javax.swing.JButton btnRequisitoCurso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
