/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author julian
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistroEscuela = new javax.swing.JButton();
        btnRegistroCurso = new javax.swing.JButton();
        btnRegistroRequisitoCorrequisito = new javax.swing.JButton();
        btnCrearPlanEstudios = new javax.swing.JButton();
        btnEliminarRequisitoCurso = new javax.swing.JButton();
        btnConsultasAdicionales = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConsultarPlanEstudios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("GESTOR PLANES ESTUDIO");

        btnRegistroEscuela.setText("Registro Escuela");
        btnRegistroEscuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroEscuelaMouseClicked(evt);
            }
        });
        btnRegistroEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEscuelaActionPerformed(evt);
            }
        });

        btnRegistroCurso.setText("Registro Curso");
        btnRegistroCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroCursoMouseClicked(evt);
            }
        });

        btnRegistroRequisitoCorrequisito.setText("Registrar Requisito o Correquisito");
        btnRegistroRequisitoCorrequisito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroRequisitoCorrequisitoMouseClicked(evt);
            }
        });

        btnCrearPlanEstudios.setText("Crear Plan Estudios");
        btnCrearPlanEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPlanEstudiosMouseClicked(evt);
            }
        });

        btnEliminarRequisitoCurso.setText("Eliminar Requisito a Curso");
        btnEliminarRequisitoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarRequisitoCursoMouseClicked(evt);
            }
        });

        btnConsultasAdicionales.setText("Consultas Adicionales");
        btnConsultasAdicionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasAdicionalesMouseClicked(evt);
            }
        });

        btnSalir.setText("salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        jLabel2.setText("Registros");

        jLabel3.setText("Consultas");

        jLabel4.setText("Modificacion de información");

        btnConsultarPlanEstudios.setText("Consultar Plan Estudios");
        btnConsultarPlanEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarPlanEstudiosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnSalir)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroRequisitoCorrequisito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearPlanEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarRequisitoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultasAdicionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultarPlanEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroEscuela)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroCurso)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroRequisitoCorrequisito)
                .addGap(18, 18, 18)
                .addComponent(btnCrearPlanEstudios)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarPlanEstudios)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultasAdicionales)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarRequisitoCurso)
                        .addContainerGap(124, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEscuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroEscuelaActionPerformed

    private void btnRegistroEscuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEscuelaMouseClicked
        // TODO add your handling code here:
      RegistroEscuela registroEscuela = new RegistroEscuela();   
      registroEscuela.setVisible(true);
      this.dispose(); 
    }//GEN-LAST:event_btnRegistroEscuelaMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
      System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistroCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCursoMouseClicked
        // TODO add your handling code here:
      RegistroCurso registroCurso = new RegistroCurso();
      registroCurso.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRegistroCursoMouseClicked

    private void btnRegistroRequisitoCorrequisitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroRequisitoCorrequisitoMouseClicked
        // TODO add your handling code here:
      RegistroRequisitoCorrequisito registroRQ = new RegistroRequisitoCorrequisito();
      registroRQ.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRegistroRequisitoCorrequisitoMouseClicked

    private void btnCrearPlanEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPlanEstudiosMouseClicked
        // TODO add your handling code here:
      RegistroPlanEstudio registroPE = new RegistroPlanEstudio();
      registroPE.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnCrearPlanEstudiosMouseClicked

    private void btnConsultarPlanEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarPlanEstudiosMouseClicked
        // TODO add your handling code here:
      ConsultarPlanEstudios consultarPE = new ConsultarPlanEstudios(); 
      consultarPE.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnConsultarPlanEstudiosMouseClicked

    private void btnConsultasAdicionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasAdicionalesMouseClicked
        // TODO add your handling code here:
      ConsultarAdicionales consultasAdi = new ConsultarAdicionales();
      consultasAdi.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnConsultasAdicionalesMouseClicked

    private void btnEliminarRequisitoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarRequisitoCursoMouseClicked
        // TODO add your handling code here:
      ModificarInformacion modificacionInfo = new ModificarInformacion(); 
      modificacionInfo.setVisible(true);
      this.dispose();      
    }//GEN-LAST:event_btnEliminarRequisitoCursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPlanEstudios;
    private javax.swing.JButton btnConsultasAdicionales;
    private javax.swing.JButton btnCrearPlanEstudios;
    private javax.swing.JButton btnEliminarRequisitoCurso;
    private javax.swing.JButton btnRegistroCurso;
    private javax.swing.JButton btnRegistroEscuela;
    private javax.swing.JButton btnRegistroRequisitoCorrequisito;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
